version: "3" 
  services: 
    client: 
      build:
       context: /home/richman/projects/rtg-devops-takehome
       dockerfile: Dockerfile
    #  volumes: # Links the source files to the running container 
    #   - /home/richman/projects/rtg-devops-takehome:/usr/src/ 
     ports: - "8080:8080"